# Generated by Django 2.0.6 on 2019-03-04 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=50)),
                ('blog_title', models.CharField(default='', max_length=50)),
                ('blog_entry', models.TextField(default='')),
            ],
        ),
    ]
